# docker compose nginx mount current directory
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./common/:/usr/share/nginx/html/common
      - ./index.html:/usr/share/nginx/html/index.html
      - ./favicon.ico:/usr/share/nginx/html/favicon.ico